# === Input and Output Paths ===
score_path: 
covariate_path:
#Both need to be saved as csv files with row and columns names
#If no covariates are included in the model set it to NULL

n_nodes:
n_basis_for_dim_recustion: 

output_path:
name_output: 

# === Model Parameters ===
L: 100
K: 5
thres_ctrl: [0, 0.2, 0.4, 0.8, 1.2, 1.6, 2.0]
tol_abs: 0.0001
tol_rel: 0.0001
eps: 0.00000001
verbose: TRUE
p_rand_lam: 0.5
p_rand_thr: 1

